[2010-10-29 16:02:07,447] (DEBUG) process.py: 31:  ./yishan_hadoop.py -s /user/daogou/indexbuilder/data/current/auction/ -d /home/admin/admin/daogou_auction/runtimedatgou_auction/daogou_auction/ > hdfs2pangu2010-10-29-1288339327.log 2>&1
[2010-10-29 16:03:43,846] (DEBUG) process.py: 31:  ./yishan_hadoop.py -s /user/daogou/indexbuilder/data/current/auction/ -d /home/admin/admin/ > hdfs2pangu2010-10-29-1288339423.log 2>&1
[2010-10-29 16:07:23,355] (DEBUG) process.py: 31:  ./yishan_hadoop.py -s /user/daogou/indexbuilder/data/current/auction/ -d /home/admin/admin/ > hdfs2pangu2010-10-29-1288339643.log 2>&1
[2010-10-29 16:43:28,259] (DEBUG) process.py: 31:  ./yishan_hadoop.py -s /user/daogou/indexbuilder/data/current/news -d /home/admin/admin/ > hdfs2pangu2010-10-29-1288341808.log 2>&1
[2010-10-29 16:46:51,718] (DEBUG) process.py: 31:  ./yishan_hadoop.py -s /user/daogou/indexbuilder/data/current/news -d /home/admin/admin/ > hdfs2pangu2010-10-29-1288342011.log 2>&1
[2010-10-29 16:58:30,587] (DEBUG) process.py: 31:  ./yishan_hadoop.py -s /user/daogou/indexbuilder/data/current/news -d /home/admin/admin/ > hdfs2pangu2010-10-29-1288342710.log 2>&1
[2010-10-29 17:00:47,255] (DEBUG) process.py: 31:  ./yishan_hadoop.py -s /user/daogou/indexbuilder/data/current/news -d /home/admin/admin/ > hdfs2pangu2010-10-29-1288342847.log 2>&1
[2010-10-29 17:09:59,335] (DEBUG) process.py: 31:  ./yishan_hadoop.py -s /user/daogou/indexbuilder/data/current/news -d /home/admin/admin/ > hdfs2pangu2010-10-29-1288343399.log 2>&1
[2010-10-29 17:15:21,000] (DEBUG) process.py: 31:  ./yishan_hadoop.py -s /user/daogou/indexbuilder/data/current/news -d /home/admin/admin/ > hdfs2pangu2010-10-29-1288343720.log 2>&1
[2010-10-31 21:51:28,654] (INFO) builddetetor.py: 15:  hello
[2010-11-01 17:43:28,671] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e /home/admin/admin/.meta
[2010-11-01 17:43:30,911] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e /home/admin/admin/.coping
[2010-11-01 17:43:52,463] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e /home/admin/admin/.meta
[2010-11-01 17:43:54,722] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e /home/admin/admin/.coping
[2010-11-01 17:49:01,391] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 17:49:12,824] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list/.meta
[2010-11-01 17:49:30,472] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list/.meta
[2010-11-01 17:49:41,437] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list/
[2010-11-01 17:50:44,972] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list/
[2010-11-01 18:01:45,179] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list/
[2010-11-01 18:19:46,264] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 18:19:48,695] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 18:19:51,129] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 18:21:17,061] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 18:21:19,342] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 18:21:21,647] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 18:23:45,890] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 18:23:48,130] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 18:23:50,386] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:47:39,363] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:47:42,657] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:47:44,978] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:47:47,303] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:47:49,623] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:57:41,946] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:57:44,193] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:57:46,672] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:57:49,168] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:59:45,665] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:59:47,922] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:59:50,196] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:59:52,459] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:59:54,734] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:59:57,006] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 21:59:59,286] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:01,547] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:03,799] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:06,075] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:08,337] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:10,584] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:12,853] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:19,168] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:21,510] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:23,881] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:26,211] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:28,559] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:30,900] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:33,251] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:35,589] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:37,937] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:40,293] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:42,634] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:44,972] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:47,317] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:49,660] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:52,009] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:54,361] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:56,717] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:00:59,063] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:01:01,613] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:01:04,153] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:01:06,476] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:01:09,020] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:13:44,935] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:13:47,178] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:13:49,435] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:13:51,690] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:13:53,952] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:13:56,199] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:13:58,465] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:14:00,722] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:14:02,985] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:14:05,244] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:14:07,509] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:14:09,762] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:14:12,023] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:52:40,158] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:52:42,620] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:52:45,101] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:58:36,263] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_list
[2010-11-01 22:58:43,640] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 22:58:46,021] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 22:58:48,589] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 22:58:51,147] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 22:58:53,702] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 22:58:56,256] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 22:58:58,636] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 22:59:00,972] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 22:59:03,461] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 22:59:06,005] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 22:59:08,590] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/backup/news/partition_0/version_lis
[2010-11-01 23:04:04,006] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:06,285] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:08,572] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:10,846] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:13,143] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:15,421] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:17,724] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:20,013] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:22,316] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:24,606] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:26,904] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:29,184] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:31,489] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:33,774] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:36,071] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:38,348] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:40,650] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:42,927] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:45,217] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:47,503] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:49,797] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:52,085] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:54,381] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:56,663] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:04:58,949] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:01,234] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:03,546] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:05,833] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:08,132] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:10,402] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:12,701] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:14,990] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:17,281] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:19,562] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:21,862] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:24,145] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:26,632] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:28,915] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:31,214] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:33,500] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:35,792] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:38,065] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:40,361] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:42,650] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:44,928] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:47,201] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:49,508] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:51,794] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:54,102] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:56,378] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:05:58,670] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:00,958] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:03,260] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:05,537] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:08,031] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:10,315] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:12,596] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:15,083] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:17,383] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:19,650] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:21,954] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:24,229] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:26,511] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:28,801] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:31,103] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:33,374] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:35,666] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:37,946] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:40,230] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:42,515] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:44,819] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:47,082] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:49,385] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:51,668] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:53,957] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:56,262] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:06:58,568] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:07:00,846] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:07:03,148] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:07:05,440] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:07:07,733] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:07:10,013] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:07:12,310] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-01 23:07:14,604] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/.done
[2010-11-02 13:27:41,444] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:27:43,928] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:27:46,414] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:27:48,677] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:27:51,166] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:27:53,641] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:27:56,132] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:27:58,605] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:37:33,291] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:46:14,169] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:48:36,834] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:51:15,077] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:51:46,363] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:51:48,603] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.meta
[2010-11-02 13:51:50,853] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 13:51:53,098] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.meta
[2010-11-02 14:37:45,390] (ERROR) controller.py: 54:  Controller instance has no attribute 'hdt'
[2010-11-02 14:43:29,888] (ERROR) controller.py: 58:  Controller instance has no attribute 'hdt'
[2010-11-02 14:45:33,512] (ERROR) controller.py: 60:  global name 'fn' is not defined
[2010-11-02 14:46:03,439] (ERROR) controller.py: 60:  global name 'timeout' is not defined
[2010-11-02 14:46:13,691] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:16,181] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:18,676] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:20,941] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:24,438] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:26,752] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:29,250] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:31,751] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:34,246] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:36,746] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:39,250] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:41,746] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:44,250] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:46,910] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:49,411] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:51,910] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:54,409] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:56,909] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:46:59,412] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 14:47:01,891] (ERROR) controller.py: 60:  Got break files: /tmp/nowait QUIT
[2010-11-02 14:47:09,760] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:12:42,473] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:12:45,750] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:12:48,237] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:12:57,530] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:12:59,794] (INFO) controller.py: 54:  Got break files: /tmp/nowait QUIT
[2010-11-02 15:12:59,794] (INFO) controller.py: 61:  Got break files: /tmp/nowait QUIT
[2010-11-02 15:13:39,588] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:13:41,829] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:13:44,082] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:13:46,372] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:13:48,795] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:13:51,241] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:13:53,661] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:13:55,907] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:13:58,328] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:14:00,774] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:14:03,030] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:14:05,280] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:14:07,530] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:14:09,780] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:14:12,028] (INFO) controller.py: 60:  Got break files: /tmp/nowait QUIT
[2010-11-02 15:14:16,428] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:14:18,707] (INFO) controller.py: 60:  got signal file from hadoop
[2010-11-02 15:14:59,774] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:15:02,017] (INFO) controller.py: 60:  got signal file from hadoop
[2010-11-02 15:15:20,809] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:15:23,080] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:15:25,351] (DEBUG) process.py: 23:  ./hadoop_client/bin/hadoop dfs -test -e hdfs://10.249.69.101:9000/user/daogou/indexbuilder/data/current/.done
[2010-11-02 15:15:28,630] (INFO) controller.py: 60:  got signal file from hadoop
[2010-11-02 17:51:38,097] (DEBUG) hadoop_copyer.py: 26:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src
[2010-11-02 17:51:38,097] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_bbs/.done
[2010-11-02 17:51:40,125] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_bbs/.meta
[2010-11-02 17:51:42,171] (DEBUG) hadoop_copyer.py:185:  path [/user/daogou/indexbuilder/data/current/dump_bbs] is not ready
[2010-11-02 17:51:42,171] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_auction/.done
[2010-11-02 17:51:44,225] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_auction/.meta
[2010-11-02 17:51:46,335] (DEBUG) hadoop_copyer.py:185:  path [/user/daogou/indexbuilder/data/current/dump_auction] is not ready
[2010-11-02 17:51:46,335] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_news/.done
[2010-11-02 17:51:48,325] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_news/.meta
[2010-11-02 17:51:50,421] (DEBUG) hadoop_copyer.py:185:  path [/user/daogou/indexbuilder/data/current/dump_news] is not ready
[2010-11-02 17:51:50,422] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_comment_record/.done
[2010-11-02 17:51:52,477] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_comment_record/.meta
[2010-11-02 17:51:54,495] (DEBUG) hadoop_copyer.py:185:  path [/user/daogou/indexbuilder/data/current/dump_comment_record] is not ready
[2010-11-02 17:51:54,496] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_question/.done
[2010-11-02 17:51:56,590] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_question/.meta
[2010-11-02 17:51:58,893] (DEBUG) hadoop_copyer.py:185:  path [/user/daogou/indexbuilder/data/current/dump_question] is not ready
[2010-11-02 17:52:08,893] (DEBUG) process.py: 23:  /apsarapangu/disk5/daogou/crontab/pe_code/index_switcher/src/hadoop_client/bin/hadoop dfs -test -e /user/daogou/indexbuilder/data/current/dump_bbs/.done
